language: python
python:
    - 3.6

services:
    - postgresql

addons:
  postgresql: 9.6

before_script:
    - pip install psycopg2
    - pip install sqlalchemy
    - pip install pycurl
    - pip install isodate
    - pip install json-rpc
    - pip install psutil
    - sudo -u postgres createuser -s -d -l admin
    - psql -c "alter user admin login;" -U postgres
    - psql -c 'CREATE DATABASE xmusic' -U postgres
    - psql -U postgres -d xmusic -a -f doc/db.sql

script:
    - python3 daemon/unittestdbservicetestcase.py
    - python3 daemon/unittestalbumrepotestcase.py
    - python3 daemon/unittestdbservicetestcase.py
    - python3 daemon/unittesttrackrepotestcase.py
